### ISSUE TITLE
РК 1

### ISSUE THREAD

**Issue by DmitryDorofeev** [frontend-park-mail-ru/2018_2_42#7]
- [x] линковать контейнеры вместо использования хостовой сети

- [x] не нажимабельны кнопки вне текста

- [x] выпилить onclick

- [x] добавить актуальную ссылку на игру в репу

**Comment by reo7sp** [comment]
А баллов доставят за фиксы?

**Comment by reo7sp** [comment]
а, все, увидел 10 из 10 за продукт
